# Generated by Django 4.2.6 on 2023-10-28 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autentikasi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
