# Generated by Django 4.2.6 on 2023-10-29 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pencarian_buku', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
