# Generated by Django 4.2.6 on 2023-10-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halaman_buku', '0002_book_sha256sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ulasan',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
